import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppProviders from "@/components/provider/mainAppProviders";
import Navbar from "@/components/Navbar/navbar";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden bg-background`}
      >
        <AppProviders>
          <Navbar />
          <ToastContainer position="top-right" />
          <div className="p-3 max-h-[93vh] flex h-full w-full">
          {children}
          </div>
        </AppProviders>
      </body>
    </html>
  );
}
